export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const MENU_SELECTED = 'MENU_SELECTED'
export const MENU_HOME = 'MENU_HOME'
export const MENU_NEXT = 'MENU_NEXT'
export const SET_COLOR = 'SET_COLOR'

export const RESIDENTS_LOADED = 'RESIDENTS_LOADED'
export const RESIDENT_SELECTED = 'RESIDENT_SELECTED'
export const RESIDENT_LOADED = 'RESIDENT_LOADED'
